"""Generic tests for backend methods.

.. codeauthor:: David Zwicker <david.zwicker@ds.mpg.de>
"""

from __future__ import annotations

import pytest
from scipy import stats

from pde import ScalarField, UnitGrid

ALL_BACKENDS = ["numpy", "numba", "jax", "torch-cpu", "torch-mps", "torch-cuda"]


@pytest.mark.parametrize("backend", ALL_BACKENDS, indirect=True)
def test_random_noise_basic(backend, rng):
    """Test random noise generated by backend."""
    field = ScalarField(UnitGrid([10_000]))
    noise = backend.make_gaussian_noise(field, rng=rng)

    data = backend.native_to_numpy(noise())
    test_res = stats.kstest(data, "norm", args=(0, 1))
    assert test_res.pvalue > 0.01  # expect Gaussian distribution
