"""
Contains the version information of the package

.. codeauthor:: David Zwicker <david.zwicker@ds.mpg.de>
"""

from pde.tools.config import check_package_version

__version__ = "0.16.5"

# The code below is generated by scripts/create_requirements.txt
# GENERATED CODE – anything you modify below might be overwritten automatically
check_package_version("matplotlib", "3.1.0")
check_package_version("numba", "0.50.0")
check_package_version("numpy", "1.18.0")
check_package_version("scipy", "1.4.0")
check_package_version("sympy", "1.5.0")
