name: "Check documentation"

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
